name: Android CI(Phecda)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: main

    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: 权限
      run: chmod 777 ./Android/gradlew
      
    - name: Build with Gradle
      run: ./Android/gradlew assembleRelease

    - name: 上传
      run: |
        TZ='Asia/Shanghai' timestamp=$(date +%Y%m%d%H%M%S)
        new_filename="Phecda-${timestamp}.apk"
        curl -T ${{ github.workspace }}/app/build/outputs/apk/release/*.apk http://nas.merak.xin/dav/${new_filename} --user web:831121

    - name: Upload GitHub Actions artifact of vcpkg build
      uses: actions/upload-artifact@v4
      with:
        name: scene-dev
        path: ${{ github.workspace }}/app/build/outputs/apk/release/*.apk